### ISSUE TITLE
Database setup and server implementation

### ISSUE THREAD

**Issue by BishanWebeshete** [BishanWebeshete/Restaurant-Reviewer#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
- This will be just to set up the application

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Follow the instructions on creating/testing full project setup
- [ ] After following the guidelines set up the server.js file
     -  [ ] create server.js
     -  [ ] app.listen on process.evn.PORT
     -  [ ] app.use(express)
     - [ ] app.use(express.static('public')
     - [ ] app.use(cors({origin: '*'})
     - [ ] include pg
- [ ] Right now focus on restaurant routes... will implement review routes later
     - [ ] get route for /api/restaurants
     -  [ ] get route for /api/restaurants/:id
     - [ ] post route for /api/restaurants
     - [ ] put route for api/restaurants/:id
     - [ ] delete route for api/restaurants/:id 
 - [ ] query db properly with its respective route to manipulate db

### 🧑‍⚕️ Clean Up Tasks
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
